#!/usr/bin/env python3
"""Generate .luacheckrc from the scraped API index.

Hand-maintaining a list of 190-odd Shroud* symbols would rot the first time the
client's API changed. This derives it from docs/api-index.json, which
tools/genindex.py builds from the vendored reference, so `./run.sh scrape`
refreshes the linter's idea of the API along with the docs.

The enums are declared with their member lists too, so `UI.Panle` is caught the
same way a misspelled function is.

Usage: python3 tools/genglobals.py
"""

import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INDEX = os.path.join(ROOT, "docs", "api-index.json")
OUTPUT = os.path.join(ROOT, ".luacheckrc")

# MoonSharp implements Lua 5.2 semantics. Linting against 5.2 rather than the
# 5.4 the offline harness happens to run means a 5.3-or-later builtin that the
# game would not have gets flagged here instead of failing in the client.
STD = "lua52"

# Present under MoonSharp and 5.1 but not in the lua52 std. Both are resolved
# with a `newName or oldName` fallback so the code runs on either: core/timers
# needs `table.unpack or unpack`, core/settings needs `load or loadstring`.
EXTRA_READ_GLOBALS = ["unpack", "loadstring"]

# Defined by tests/runner.lua and used across the specs.
SPEC_GLOBALS = [
    "describe", "it", "before_each", "after_each", "pending", "assert_that",
]


def load_index():
    if not os.path.exists(INDEX):
        print("docs/api-index.json missing - run tools/genindex.py first", file=sys.stderr)
        sys.exit(1)
    with open(INDEX, encoding="utf-8") as fh:
        return json.load(fh)


def lua_list(names, indent):
    pad = " " * indent
    return "\n".join('%s"%s",' % (pad, name) for name in names)


def main():
    data = load_index()

    # Callbacks are written by the addon, not read from the host, so they are
    # declared as writable globals rather than read-only ones.
    callbacks = sorted(
        e["name"] for e in data["entries"] if e["kind"] == "callback"
    )
    api = sorted(
        e["name"] for e in data["entries"]
        if e["kind"] in ("function", "global") and e["name"].startswith(("Shroud", "Invalid"))
    )
    # Un-prefixed aliases the reference keeps for older addons.
    aliases = ["ConsoleLog", "GetStatCount", "GetStatValueByNumber",
               "GetStatNameByNumber", "GetStatValueByName"]

    enums = data.get("enums", {})

    lines = [
        "-- Generated by tools/genglobals.py from docs/api-index.json.",
        "-- Do not edit by hand; run ./run.sh scrape to refresh both.",
        "--",
        "-- Linted against %s because MoonSharp implements Lua 5.2 semantics." % STD,
        "-- The offline harness runs 5.4, so anything newer than 5.2 would work",
        "-- in tests and fail in the client.",
        "",
        'std = "%s"' % STD,
        "max_line_length = 120",
        "",
        "-- The host's API surface: %d symbols plus %d enums."
        % (len(api) + len(aliases), len(enums)),
        "read_globals = {",
        lua_list(api + aliases + EXTRA_READ_GLOBALS, 4),
    ]

    for enum, members in sorted(enums.items()):
        lines.append("    %s = { fields = {" % enum)
        lines.append(lua_list(members, 8))
        lines.append("    } },")
    lines.append("}")
    lines.append("")

    lines += [
        "-- Callbacks the addon defines for the host to find.",
        "globals = {",
        lua_list(callbacks, 4),
        "}",
        "",
        "-- Library and plugin code must not create globals: every enabled addon",
        "-- shares one environment, so a stray name can collide with another",
        "-- author's addon. Entry points are published through _G[name], which is",
        "-- an index rather than a global assignment, so this stays strict.",
        'files["core/*.lua"] = { allow_defined_top = false }',
        'files["plugins/*/src/*.lua"] = { allow_defined_top = false }',
        "",
        "-- tests/runner.lua defines the spec DSL; the specs consume it.",
        'files["tests/**/*.lua"] = {',
        "    globals = {",
        lua_list(SPEC_GLOBALS, 8),
        "    },",
        "}",
        "",
        'files["tools/*.lua"] = { globals = { "arg" } }',
        "",
        "exclude_files = { \"dist/\", \".tooling/\" }",
        "",
    ]

    with open(OUTPUT, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))

    print(".luacheckrc: %d API symbols, %d callbacks, %d enums"
          % (len(api) + len(aliases), len(callbacks), len(enums)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
